export const menus = [
  {
    id: '1',
    name: 'scotched egg',
    menu: 'breakfast',
    img: require('../app/images/breakFast-egg.jpg'),
    amount: '#450.99',
    single: false,
  },
  {
    id: '2',
    name: 'chicken laps',
    menu: 'dinner',
    img: require('../app/images/chickenLap.jpg'),
    amount: '#599.99',
    single: true,
  },
  {
    id: '3',
    name: 'bugger and veggies',
    menu: 'dessert',
    img: require('../app/images/dessertBurger.jpg'),
    amount: '#1200.92',
    single: false,
  },
  {
    id: '4',
    name: 'cake and strawberries',
    menu: 'dessert',
    img: require('../app/images/dessertCake.jpg'),
    amount: '#950.99',
    single: false,
  },
  {
    id: '5',
    name: 'sharwama',
    menu: 'dessert',
    img: require('../app/images/fast-food.jpg'),
    amount: '#999.99',
    single: true,
  },
  {
    id: '6',
    name: 'bugger chips and drink',
    menu: 'dessert',
    img: require('../app/images/fast-food-burger.jpeg'),
    amount: '#1150.50',
    single: false,
  },
  {
    id: '7',
    name: 'fish egg and veggies',
    menu: 'breakfast',
    img: require('../app/images/fish.jpg'),
    amount: '#950.50',
    single: false,
  },
  {
    id: '8',
    name: 'fried rice salad and 2 piece of meat',
    menu: 'any',
    img: require('../app/images/Fried-riceComplete.jpg'),
    amount: '#2450.50',
    single: false,
  },
  {
    id: '9',
    name: 'fried rice and fish',
    menu: 'any',
    img: require('../app/images/friedRice-fish.jpeg'),
    amount: '#1050.50',
    single: false,
  },
  {
    id: '10',
    name: 'fried rice',
    menu: 'any',
    img: require('../app/images/Fried-Rice-only.jpg'),
    amount: '#550.50',
    single: true,
  },
  {
    id: '11',
    name: 'full chicken and veggies',
    menu: 'any',
    img: require('../app/images/fullchicken.jpeg'),
    amount: '#3250.50',
    single: false,
  },
  {
    id: '12',
    name: '5 pieces of grilled chicken',
    menu: 'dessert',
    img: require('../app/images/grilledChicken.jpg'),
    amount: '#4750.50',
    single: false,
  },
  {
    id: '13',
    name: '2 slices of pizza',
    menu: 'dessert',
    img: require('../app/images/pizza.jpg'),
    amount: '#880.50',
    single: false,
  },
  {
    id: '14',
    name: 'jollof rice with 2 chicken',
    menu: 'any',
    img: require('../app/images/rice2.jpg'),
    amount: '#2359.99',
    single: false,
  },
  {
    id: '15',
    name: 'spaghetti with chicken',
    menu: 'any',
    img: require('../app/images/spag-complete.jpg'),
    amount: '#2159.99',
    single: false,
  },
  {
    id: '16',
    name: 'veggies pasta',
    menu: 'veggies',
    img: require('../app/images/veggi-2.jpg'),
    amount: '#990.50',
    single: false,
  },
  {
    id: '17',
    name: 'stewed rice dodo and chicken',
    menu: 'any',
    img: require('../app/images/white-rice-complete.jpg'),
    amount: '#1899.99',
    single: false,
  },
  {
    id: '18',
    name: 'a bottle of wine',
    menu: 'drinks',
    img: require('../app/images/Wine1.png'),
    amount: '#1340.75',
    single: true,
  },
  {
    id: '19',
    name: 'a cup of wine',
    menu: 'drinks',
    img: require('../app/images/wineCup.jpg'),
    amount: '#400.50',
    single: true,
  },
  {
    id: '20',
    name: 'a bottle of wine1',
    menu: 'drinks',
    img: require('../app/images/Wine1.png'),
    amount: '#1340.75',
    single: false,
  },
];
